name: Train Model CI

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/train.yml'
  workflow_dispatch:

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run .
